### ISSUE TITLE
error when using validate_message with repeated field

### ISSUE THREAD

**Issue by felippe-mendonca** [labviros/is-msgs#2]
I'd had the error below when using the function [validate_message](https://github.com/labviros/is-msgs/blob/modern-cmake/is/utils/validate.hpp) with a message containing another message with repeated field.

`[libprotobuf FATAL /home/conan/.conan/data/protobuf/3.5.2/bincrafters/stable/build/4d887c1c2779c63d2cdd81580698d2e22cb35b29/source_subfolder/src/google/protobuf/generated_message_reflection.cc:101] Protocol Buffer reflection usage error:`
`  Method      : google::protobuf::Reflection::GetMessage`
`  Message type: is.vision.BoundingPoly`
`  Field       : is.vision.BoundingPoly.vertices`
`  Problem     : Field is repeated; the method requires a singular field.`
`terminate called after throwing an instance of 'google::protobuf::FatalException'`
`  what():  Protocol Buffer reflection usage error:`
`  Method      : google::protobuf::Reflection::GetMessage`
`  Message type: is.vision.BoundingPoly`
`  Field       : is.vision.BoundingPoly.vertices`
`  Problem     : Field is repeated; the method requires a singular field.`
`fish: “./build/bin/image-viewer.bin” terminated by signal SIGABRT (Abort)`

> Message used:

`syntax = "proto3";`
`import "is/msgs/camera.proto";`
`message Options {`
`  string broker_uri = 1;`
`  int32 camera_id = 2;`
`  is.vision.CameraConfig camera_config = 3;`
`  float scale = 4;`
`}`

**Comment by rodolfo-picoreti** [comment]
fixed by 160f479f21bc80d26ffb01de7076ff8e8ec5572e
